### ISSUE TITLE
_lineStrengths.py fails 

### ISSUE THREAD

**Issue by drtobybrown** [geckos-survey/gist-geckos#14]
_lineStrengths: could not broadcast input array from shape (11,) into shape (379,)
Traceback (most recent call last):
  File "/arc/home/thbrown/mauve/dev/gist-geckos/gistPipeline/lineStrengths/_lineStrengths.py", line 49, in lineStrengths_Module
    module.measureLineStrengths(config)
  File "/arc/home/thbrown/mauve/dev/gist-geckos/gistPipeline/lineStrengths/default.py", line 298, in measureLineStrengths
    redshift[:,0] = np.array( ppxf_data.V[:] ) / cvel          # Redshift

**Comment by jessevdsande** [comment]
Identified origin of lineStrengths module bug that was due to a bug in ppxf_util.gaussian_filter1d(). Bug will be fixed in version 8.2.5 of pPXF. In older pPXF version replace line 665 in ppxf_util.py with "p = int(1.0 + 4*np.max(sig))"
